version: '3'

services:
  mkdocs:
    image: mkdocs-material-mkdocs:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: mkdocs_devops_docs
    restart: unless-stopped
    # ports:
    #   - "8000:8000"
    volumes:
      - ${PWD}:/root
    stdin_open: true
    tty: true
    command:
      - "mkdocs"
      - "serve"
      - "--dev-addr=0.0.0.0:8000"
      - "--config-file"
      - "./mkdocs-sample.yml"
    networks:
      - my_app_network
networks:
  my_app_network:
    external: true
    name: cloudflare_redisinsight_app-network
